import pyautogui as gui
import time
import os

os.startfile (r'C:\Users\casa\AppData\Local\WhatsApp\WhatsApp.exe')
print('Abrindo whatsapp')
time.sleep(10)
print('1')
print('2')
print('3')
print('4')
print('5')
print('6')
print('7')
print('8')
print('9')
print('10')
while True:
     time.sleep(5)
     step1 = gui.locateCenterOnScreen('circulo2.png')
     print('localizando')
     gui.click(step1)
     print('abrindo mensagem')
     time.sleep(2)
     gui.write('Oi amor, te amo!')
     print('respondendo')
     step2 = gui.locateCenterOnScreen('seta.png')
     print('localizando botão de envio')
     gui.click(step2)
     print('clicando botão de envio')
     gui.moveTo(x=205, y=576)
     gui.click(x=205, y=576)
     time.sleep(5)
     step3 = gui.locateCenterOnScreen('fechar.png')
     gui.click(step3)
     time.sleep(10)
     
     os.startfile (r'C:\Users\joao\AppData\Local\WhatsApp\WhatsApp.exe')
print('Abrindo whatsapp')
